import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    nav_listings: "Listings",
    nav_buy: "Buy",
    nav_sell: "Sell",
    nav_news: "News",
    hero_title: "Find the Property of Your Dreams",
    hero_subtitle: "Discover the perfect property or connect with eager buyers. Your journey starts here.",
    hero_buy_btn: "Search Property",
    hero_sell_btn: "Receive Professional Proposals",
    featured_title: "Featured Properties",
    featured_subtitle: "Explore our most exclusive and sought-after listings available right now.",
    agents_title: "Featured Agents",
    agents_subtitle: "Work with the top-rated real estate professionals in the industry.",
    why_title: "Why Choose Lister?",
    why_subtitle: "We offer a seamless experience for both buyers and sellers, with advanced search filters, expert guidance, and a secure platform for all your real estate needs.",
    feature_1_title: "Vast Listings",
    feature_1_desc: "Explore thousands of properties tailored to your preferences.",
    feature_2_title: "Expert Agents",
    feature_2_desc: "Connect with experienced agents ready to assist you.",
    feature_3_title: "Secure Transactions",
    feature_3_desc: "Our platform ensures safe and transparent dealings.",
    footer_rights: "All rights reserved.",
    login_buyer_title: "Buyer Login",
    login_seller_title: "Seller Login",
    login_welcome: "Welcome Back!",
    login_buyer_desc: "Sign in to find and save your favorite homes.",
    login_seller_desc: "Access your dashboard to manage your property listings.",
    login_generic_desc: "Choose your path to continue.",
    signup_title: "Create Account",
    signup_desc: "Join Lister to start your real estate journey.",
    label_email: "Email",
    label_password: "Password",
    btn_login_buyer: "Login as Buyer",
    btn_login_seller: "Login as Seller",
    btn_signup: "Sign Up",
    btn_switch_buyer: "Switch to Buyer Login",
    btn_switch_seller: "Switch to Seller Login",
    signup_prompt: "Don't have an account?",
    login_prompt: "Already have an account?",
    signup_link: "Sign Up",
    login_link: "Login",
    listings_title: "Discover Your Next Property",
    listings_subtitle: "Explore our hand-picked selection of properties, from cozy apartments to spacious family homes. Find the perfect place that fits your lifestyle.",
    listings_not_found: "Can't find what you're looking for?",
    listings_contact: "Contact us",
    listings_contact_suffix: "for personalized assistance!",
    search_title: "Search Properties",
    search_subtitle: "Select an area on the map and apply filters to find your perfect property",
    search_filters: "Filters",
    search_price_range: "Price Range",
    search_bedrooms: "Bedrooms",
    search_bathrooms: "Bathrooms",
    search_property_type: "Property Type",
    search_any: "Any",
    search_house: "House",
    search_apartment: "Apartment",
    search_condo: "Condo",
    search_townhouse: "Townhouse",
    search_button: "Search Properties",
    search_select_area: "Select Search Area",
    search_select_area_desc: "Draw a rectangle on the map to define your search area",
    news_title: "Real Estate News & Insights",
    news_subtitle: "Stay informed with the latest trends, tips, and updates from the real estate world",
    news_search_placeholder: "Search articles...",
    news_category_all: "All",
    news_category_market: "Market Trends",
    news_category_tips: "Buying Tips",
    news_category_trends: "Design Trends",
    news_category_investment: "Investment",
    news_category_legal: "Legal",
    news_category_tech: "Technology",
    news_read_more: "Read More",
    news_no_results: "No articles found",
    news_newsletter_title: "Subscribe to Our Newsletter",
    news_newsletter_subtitle: "Get the latest real estate news and insights delivered to your inbox",
    news_newsletter_placeholder: "Enter your email",
    news_newsletter_button: "Subscribe",
    news_post_1_title: "The Future of Real Estate: 2026 Market Predictions",
    news_post_1_excerpt: "Explore the key trends shaping the real estate market this year, from sustainable homes to remote work impact on property values.",
    news_post_2_title: "10 Essential Tips for First-Time Home Buyers",
    news_post_2_excerpt: "Navigate the home buying process with confidence. Learn about financing, inspections, and making the right offer.",
    news_post_3_title: "Modern Home Design Trends Taking Over 2026",
    news_post_3_excerpt: "Discover the hottest interior and exterior design trends that are transforming homes this year.",
    news_post_4_title: "Investment Properties: Maximizing Your Returns",
    news_post_4_excerpt: "Smart strategies for real estate investors looking to maximize rental income and property appreciation.",
    news_post_5_title: "Understanding Property Laws: A Complete Guide",
    news_post_5_excerpt: "Everything you need to know about property rights, contracts, and legal obligations in real estate transactions.",
    news_post_6_title: "How Technology is Revolutionizing Property Search",
    news_post_6_excerpt: "From virtual tours to AI-powered recommendations, see how tech is changing the way we find homes."
  },
  pt: {
    nav_listings: "Anúncios",
    nav_buy: "Comprar",
    nav_sell: "Vender",
    nav_news: "Notícias",
    hero_title: "Encontre o Imovel dos seus sonhos",
    hero_subtitle: "Descubra a propriedade perfeita ou conecte-se com compradores interessados. Sua jornada começa aqui.",
    hero_buy_btn: "Procurar Propriedade",
    hero_sell_btn: "Receber propostas Profissionais",
    featured_title: "Imóveis em Destaque",
    featured_subtitle: "Explore nossos anúncios mais exclusivos e procurados disponíveis agora.",
    agents_title: "Agentes em Destaque",
    agents_subtitle: "Trabalhe com os profissionais imobiliários mais bem avaliados do setor.",
    why_title: "Por que escolher a Lister?",
    why_subtitle: "Oferecemos uma experiência perfeita para compradores e vendedores, com filtros de pesquisa avançados, orientação especializada e uma plataforma segura para todas as suas necessidades imobiliárias.",
    feature_1_title: "Vastos Anúncios",
    feature_1_desc: "Explore milhares de propriedades adaptadas às suas preferências.",
    feature_2_title: "Agentes Especialistas",
    feature_2_desc: "Connecte-se com agentes experientes prontos para ajudá-lo.",
    feature_3_title: "Transações Seguras",
    feature_3_desc: "Nossa plataforma garante negociações seguras e transparentes.",
    footer_rights: "Todos os direitos reservados.",
    login_buyer_title: "Login do Comprador",
    login_seller_title: "Login do Vendedor",
    login_welcome: "Bem-vindo de volta!",
    login_buyer_desc: "Faça login para encontrar e salvar suas casas favoritas.",
    login_seller_desc: "Acesse seu painel para gerenciar seus anúncios de imóveis.",
    login_generic_desc: "Escolha seu caminho para continuar.",
    signup_title: "Criar Conta",
    signup_desc: "Junte-se à Lister para começar sua jornada imobiliária.",
    label_email: "E-mail",
    label_password: "Senha",
    btn_login_buyer: "Entrar como Comprador",
    btn_login_seller: "Entrar como Vendedor",
    btn_signup: "Cadastrar",
    btn_switch_buyer: "Mudar para Login de Comprador",
    btn_switch_seller: "Mudar para Login de Vendedor",
    signup_prompt: "Não tem uma conta?",
    login_prompt: "Já tem uma conta?",
    signup_link: "Cadastre-se",
    login_link: "Entrar",
    listings_title: "Descubra sua Próxima Propriedade",
    listings_subtitle: "Explore nossa seleção escolhida a dedo de propriedades, de apartamentos aconchegantes a casas de família espaçosas. Encontre o lugar perfeito que se adapta ao seu estilo de vida.",
    listings_not_found: "Não consegue encontrar o que procura?",
    listings_contact: "Entre em contato",
    listings_contact_suffix: "para assistência personalizada!",
    search_title: "Procurar Propriedades",
    search_subtitle: "Selecione uma área no mapa e aplique filtros para encontrar a propriedade perfeita",
    search_filters: "Filtros",
    search_price_range: "Faixa de Preço",
    search_bedrooms: "Quartos",
    search_bathrooms: "Casas de Banho",
    search_property_type: "Tipo de Propriedade",
    search_any: "Qualquer",
    search_house: "Casa",
    search_apartment: "Apartamento",
    search_condo: "Condomínio",
    search_townhouse: "Moradia",
    search_button: "Procurar Propriedades",
    search_select_area: "Selecionar Área de Pesquisa",
    search_select_area_desc: "Desenhe um retângulo no mapa para definir a sua área de pesquisa",
    news_title: "Notícias e Insights Imobiliários",
    news_subtitle: "Mantenha-se informado com as últimas tendências, dicas e atualizações do mundo imobiliário",
    news_search_placeholder: "Pesquisar artigos...",
    news_category_all: "Todos",
    news_category_market: "Tendências de Mercado",
    news_category_tips: "Dicas de Compra",
    news_category_trends: "Tendências de Design",
    news_category_investment: "Investimento",
    news_category_legal: "Legal",
    news_category_tech: "Tecnologia",
    news_read_more: "Ler Mais",
    news_no_results: "Nenhum artigo encontrado",
    news_newsletter_title: "Subscreva a Nossa Newsletter",
    news_newsletter_subtitle: "Receba as últimas notícias e insights imobiliários na sua caixa de entrada",
    news_newsletter_placeholder: "Digite seu e-mail",
    news_newsletter_button: "Subscrever",
    news_post_1_title: "O Futuro do Imobiliário: Previsões de Mercado para 2026",
    news_post_1_excerpt: "Explore as principais tendências que moldam o mercado imobiliário este ano, desde casas sustentáveis até o impacto do trabalho remoto nos valores dos imóveis.",
    news_post_2_title: "10 Dicas Essenciais para Compradores de Primeira Viagem",
    news_post_2_excerpt: "Navegue pelo processo de compra de casa com confiança. Aprenda sobre financiamento, inspeções e como fazer a oferta certa.",
    news_post_3_title: "Tendências de Design Moderno Dominando 2026",
    news_post_3_excerpt: "Descubra as tendências de design interior e exterior mais quentes que estão transformando casas este ano.",
    news_post_4_title: "Propriedades de Investimento: Maximizando Seus Retornos",
    news_post_4_excerpt: "Estratégias inteligentes para investidores imobiliários que procuram maximizar a renda de aluguel e valorização de propriedades.",
    news_post_5_title: "Compreender as Leis de Propriedade: Um Guia Completo",
    news_post_5_excerpt: "Tudo o que você precisa saber sobre direitos de propriedade, contratos e obrigações legais em transações imobiliárias.",
    news_post_6_title: "Como a Tecnologia Está Revolucionando a Busca de Propriedades",
    news_post_6_excerpt: "De tours virtuais a recomendações baseadas em IA, veja como a tecnologia está mudando a forma como encontramos casas."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};